version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "BESTSELLER/engineering-services"
    labels:
      - dependencies
    groups:
      k8s:
        patterns:
          - " k8s.io/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "BESTSELLER/engineering-services"
    labels:
      - dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "BESTSELLER/engineering-services"
    labels:
      - dependencies
