version: 2.1

orbs:
  secret-injector: bestsellerit/secret-injector@2.5.1
  cci-common: bestsellerit/cci-common@1.13.5

prod_context: &prod_context
  context:
    - es02-prod
    - shared

workflows:
  build:
    jobs:
      - secret-injector/dump-secrets-yaml:
          secret-file: secrets-ci.yaml
          vault-oidc: true
          <<: *prod_context
      - cci-common/go_test_unit:
          go_version: "1.21.3"
          requires:
            - secret-injector/dump-secrets-yaml
      - cci-common/go_test_sonar:
          go_version: "1.21.3"
          <<: *prod_context
          requires:
            - secret-injector/dump-secrets-yaml
      - cci-common/build_n_push_docker:
          repo: public-docker
          tag: $DEPLOY_TAG
          requires:
            - cci-common/go_test_unit
            - cci-common/go_test_sonar
          <<: *prod_context
          pre-steps:
            - run:
                name: Generate Docker Tag
                command: |
                  source /tmp/secrets || true
                  source ${BASH_ENV} || true

                  if [ -z "$CIRCLE_TAG" ]; then
                    echo "export DEPLOY_TAG=0.0.0-$(echo $CIRCLE_SHA1)" >> $BASH_ENV
                  else
                    echo "export DEPLOY_TAG=$(echo $CIRCLE_TAG)" >> $BASH_ENV
                  fi
          post-steps:
            - run:
                name: i dont know
                command: |
                  source /tmp/secrets || true
                  source ${BASH_ENV} || true

                  curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer $GITHUB_TOKEN" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/actions/workflows/lint-test.yml/dispatches \
                    -d '{"ref":"'$CIRCLE_BRANCH'","inputs":{"docker_image_tag":"'$DEPLOY_TAG'"}}'
